apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: kafka-vertx-consumer
  pollingInterval: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc:9092
        consumerGroup: my_group
        topic: my-topic
        # Optional
        lagThreshold: "50"
        offsetResetPolicy: latest
